test_pedigree_price_ids = {
    "any_puppy": "price_1RtUciCYSxVmD9YE995su8aQ",
    "any_junior": "price_1RtVQxCYSxVmD9YEI97qj4qI",
    "any_gundog": "price_1RtVSBCYSxVmD9YEqFHhw5VU",
    "any_utility": "price_1RtVSnCYSxVmD9YEFsPlQeVK",
    "any_hound": "price_1RtVTHCYSxVmD9YETLfsIr4Y",
    "any_toy": "price_1RtVTXCYSxVmD9YEybMk9Rcd",
    "any_working": "price_1RtVTnCYSxVmD9YEerKUOwIq",
    "any_pastoral": "price_1RtVU2CYSxVmD9YEA42sSHWg",
    "any_terrier": "price_1RtVUDCYSxVmD9YEqs1GeKA5",
    "any_open": "price_1RtVUOCYSxVmD9YEh9zsgdy2",
    "any_veteran": "price_1RtVUgCYSxVmD9YEK2jqTc7s",
    "junior_handler": "price_1RtVUvCYSxVmD9YEviZ4B0Fd",
}

test_all_dog_price_ids = {
    "puppy": "price_1RtVV6CYSxVmD9YExqp1MW67",
    "prettiest": "price_1RtVVHCYSxVmD9YENA2Z63rt",
    "best_condition": "price_1RtVVUCYSxVmD9YEVs9i4s8U",
    "best_rescue": "price_1RtVVoCYSxVmD9YEcrYFXV0p",
    "waggiest_tale": "price_1RtVWBCYSxVmD9YEUFQA2eoV",
    "childs_best_friend": "price_1RtVWWCYSxVmD9YETdikuajE",
    "fancy_dress": "price_1RtVWyCYSxVmD9YENinX02B4",
    "handsome": "price_1RtVXxCYSxVmD9YE49X76SQL",
    "fluffiest": "price_1RtVYACYSxVmD9YEaPxTIhlK",
    "scruffiest": "price_1RtVYNCYSxVmD9YEeHvIgW8C",
    "smooth": "price_1RtVYaCYSxVmD9YERdV50ltz",
    "looks_like_owner": "price_1RtVYmCYSxVmD9YELQ5TfMz0",
    "obedience": "price_1RtVZ1CYSxVmD9YEBdfIrXsW",
    "golden_oldie": "price_1RtVZCCYSxVmD9YEz5kWymxJ",
}

pedigree_price_ids = {
    "any_puppy": "price_1Ru0CFCxiZ7gi8V55qxclT76",
    "any_junior": "price_1Ru0CCCxiZ7gi8V5eD2vuipk",
    "any_gundog": "price_1Ru0C7CxiZ7gi8V5E5WmSFtW",
    "any_utility": "price_1Ru0C5CxiZ7gi8V51TuDyVtq",
    "any_hound": "price_1Ru0C3CxiZ7gi8V5wI0uufEA",
    "any_toy": "price_1Ru0BvCxiZ7gi8V5RXdiVjVh",
    "any_working": "price_1Ru0ApCxiZ7gi8V5UVvRVcD8",
    "any_pastoral": "price_1Ru0AnCxiZ7gi8V5zddZn5XY",
    "any_terrier": "price_1Ru0AiCxiZ7gi8V5wOgR6hdL",
    "any_open": "price_1Ru0AgCxiZ7gi8V5JbzYpLHT",
    "any_veteran": "price_1Ru0AeCxiZ7gi8V5kbDwkktR",
    "junior_handler": "price_1Ru0AXCxiZ7gi8V5KGhDVpZW",
}

all_dog_price_ids = {
    "puppy": "price_1Ru08HCxiZ7gi8V5flzfJdOo",
    "prettiest": "price_1Ru08ACxiZ7gi8V5b8SHhDE4",
    "best_condition": "price_1Ru083CxiZ7gi8V5ul0lrCYF",
    "best_rescue": "price_1Ru080CxiZ7gi8V5buh1q51J",
    "waggiest_tale": "price_1Ru07vCxiZ7gi8V5N99lyhd2",
    "childs_best_friend": "price_1Ru07jCxiZ7gi8V59IjculQZ",
    "fancy_dress": "price_1Ru07XCxiZ7gi8V5ERv2G9CU",
    "handsome": "price_1Ru07RCxiZ7gi8V54aIteipH",
    "fluffiest": "price_1Ru07MCxiZ7gi8V5CmQYOEHU",
    "scruffiest": "price_1Ru07CCxiZ7gi8V5W5K1ehV3",
    "smooth": "price_1Ru076CxiZ7gi8V5Ra4HAgXG",
    "looks_like_owner": "price_1Ru06zCxiZ7gi8V55b3c8xCu",
    "obedience": "price_1Ru06qCxiZ7gi8V5xWhoqdxC",
    "golden_oldie": "price_1Ru04sCxiZ7gi8V5gGyBPvUe",
}
